train_id: no2
load_checkpoint: None

# dataset
rootdir: ./dataset
dataset: Glasgow
feature_type: v_heatmap
domain: folder # key to extract domain from .h5 file
num_classes: 6
num_train_domains: 6
num_domains: 7
val_dom: None
test_dom: 0

# train:
batch_size: 32
num_epochs: 2
ckpt_freq: 1
ckpt: None

algorithm: ERM
learning_rate: 5e-6
weight_decay: 0.1
loss_type: CrossEntropy
# DANN  
lambd: 0.1
loss_type_d: CrossEntropy
nonlinear_discriminator: True
d_steps_per_g_step: 1

# model
featurizer: MNIST_CNN
nonlinear_classifier: True
num_inputs: 1,200,251
# MLP
mlp_num_hidden: 32
mlp_dropout: 0.1
mlp_width: 64
mlp_depth: 5
# Resnet
resnet18: True
resnet_dropout: 0.1
freeze_bn: True


